# Generated by Django 4.2.5 on 2023-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
